- name: variables to print
  hosts: web
  vars:  #play level, all tasks in this play have access to this
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "ARUN KUMAR R"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

  tasks:
    - name: print the information
       vars:  #task level variables,
        COURSE: "Ansible"
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"