- name: variables to print
  hosts: web
  vars:  #lay level
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "ARUN KUMAR R"
  tasks:
    - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"